### ISSUE TITLE
Truffle-HDWallet-Provider

### ISSUE THREAD

**Issue by lowkaweiken** [imperialsoftech/coffee-supplychain-ethereum#3]
I am having issues trying to run this project. Whenever I tried to "truffle migrate" this project, this error will pop up:

_Error: Cannot find module 'truffle-hdwallet-provider'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)_

How can I resolve this issue?

**Comment by lowkaweiken** [comment]
Okay I managed to got through by executing the following 

`$ npm install truffle-hdwallet-provider`

and 

`npm install -g windows-build-tools` (in admin powershell)


Source: [From Truffle Tutorial](https://truffleframework.com/tutorials/using-infura-custom-provider)

**Comment by imperialsoftech** [comment]
Solution suggested by @lowkaweiken is correct
